services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-db:1521/testdb
      SPRING_DATASOURCE_USERNAME: temp
      SPRING_DATASOURCE_PASSWORD: temp
    depends_on:
      - h2-db

  h2-db:
    image: oscarfonts/h2
    container_name: h2db
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - h2-data:/opt/h2-data
volumes:
  h2-data: